/*
 * Program Number : 4
 * Student Name    : Yashik Jain
 * Register Number : MT2026117
 * Date            : 11-09-2026
 * Description     : Opens an existing file in read-write mode using open()
 *                    (Experiment 1), then experiments with the O_EXCL flag
 *                    in combination with O_CREAT to observe atomic
 *                    create-if-not-exists behavior (Experiment 2).
 */

#include <stdio.h>      // printf()
#include <fcntl.h>      // open() and file opening flags
#include <unistd.h>     // close()
#include <errno.h>      // errno
#include <string.h>     // strerror()

int main()
{
    int fd;

    /*
     * ============================================================
     * EXPERIMENT 1
     * ============================================================
     *
     * Open an existing file in READ-WRITE mode.
     *
     * O_RDWR means:
     *      Open the file for BOTH reading and writing.
     *
     * We are NOT using O_CREAT here.
     *
     * Therefore, test.txt must already exist for this
     * open() call to succeed.
     */

    fd = open("test.txt", O_RDWR);

    /*
     * open() returns:
     *
     *      >= 0  -> File opened successfully
     *      -1    -> Error occurred
     *
     * So we check whether fd is -1.
     */

    if (fd == -1)
    {
        /*
         * Since test.txt does not exist during our first run,
         * this will print:
         *
         *      No such file or directory
         *
         * errno contains the error number generated by open().
         *
         * strerror(errno) converts that error number into
         * a readable error message.
         */

        printf("Error opening test.txt: %s\n", strerror(errno));

        /*
         * IMPORTANT:
         *
         * We do NOT return here.
         *
         * This practical has a second experiment involving
         * O_EXCL, so we want the program to continue.
         */
    }
    else
    {
        /*
         * This block executes if test.txt already exists
         * and was successfully opened.
         */

        printf("test.txt opened successfully.\n");

        /*
         * fd is the file descriptor assigned by the OS.
         */
        printf("File descriptor = %d\n", fd);

        /*
         * We have finished using the file descriptor,
         * so we close it.
         */
        close(fd);
    }


    /*
     * ============================================================
     * EXPERIMENT 2
     * ============================================================
     *
     * Experiment with O_EXCL.
     *
     * We use:
     *
     *      O_CREAT | O_EXCL | O_RDWR
     *
     * O_CREAT:
     *      Create the file if it does not exist.
     *
     * O_EXCL:
     *      When used together with O_CREAT, make the
     *      open() fail if the file already exists.
     *
     * O_RDWR:
     *      Open the file for both reading and writing.
     *
     * Therefore:
     *
     *      O_CREAT | O_EXCL | O_RDWR
     *
     * means:
     *
     * "Create test.txt for reading and writing, but
     *  fail if test.txt already exists."
     *
     *
     * 0644:
     *
     * This is the permission mode used when the file is
     * actually created.
     *
     * 6 -> Owner:  read + write
     * 4 -> Group:  read only
     * 4 -> Others: read only
     */

    fd = open("test.txt", O_CREAT | O_EXCL | O_RDWR, 0644);


    /*
     * Check whether the O_EXCL experiment succeeded.
     */

    if (fd == -1)
    {
        /*
         * If test.txt already exists, O_EXCL causes open()
         * to fail.
         *
         * The expected error is:
         *
         *      File exists
         */

        printf("O_EXCL failed: %s\n", strerror(errno));
    }
    else
    {
        /*
         * If test.txt did NOT exist, O_CREAT creates it
         * successfully.
         */

        printf("File created successfully using O_EXCL.\n");

        /*
         * Display the file descriptor assigned by the OS.
         */
        printf("File descriptor = %d\n", fd);

        /*
         * Close the file descriptor because we are
         * finished using the file.
         */
        close(fd);
    }


    /*
     * Return 0 indicates that the program completed normally.
     */

    return 0;
}


/* SAMPLE O/P
yashik@LAPTOP-UV7S5VGB:~/linux-learning/02-HOL1/prac-04$ ./4
Error opening test.txt: No such file or directory
File created successfully using O_EXCL.
File descriptor = 3


yashik@LAPTOP-UV7S5VGB:~/linux-learning/02-HOL1/prac-04$ ./4
test.txt opened successfully.
File descriptor = 3
O_EXCL failed: File exists

*/